### ISSUE TITLE
Trouble with the square.js example

### ISSUE THREAD

**Issue by csajedi** [elavoie/pando-handbook#2]
Hello Eric,

This might be my own inexperience with node, but I  cannot seem to get the example in the readme (`pando suquare.js ...`) to execute on my linux machine. 

## Environment context:
linux machine
`node -v -> v10.16.0`

## Steps to reproduce:

* `git clone https://github.com/elavoie/pando-computing
cd pando-computing
npm install && npm link
`
* `cd examples`
* `pando square.js 1 2 3 4 5 6 7 8 9 10`

output:

> pando square.js 1 2 3 4 5 6 7 8 9 10
events.js:174
      throw er; // Unhandled 'error' event
      ^

>Error: electron-eval error: Electron process exited with code 1
    at ChildProcess.<anonymous> (/home/cam/code/automatacoin/pando/pando-computing/node_modules/electron-eval/lib/index.js:174:22)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
>Emitted 'error' event at:
    at Daemon.error (/home/cam/code/automatacoin/pando/pando-computing/node_modules/electron-eval/lib/index.js:101:12)
    at ChildProcess.<anonymous> (/home/cam/code/automatacoin/pando/pando-computing/node_modules/electron-eval/lib/index.js:174:16)
    at ChildProcess.emit (events.js:198:13)
    [... lines matching original stack trace ...]
    at Pipe._handle.close (net.js:606:12)

When I run `npm run test` I get no indication of anything wrong:

> pando-computing@0.17.14 test /home/cam/code/automatacoin/pando/pando-computing
> tape test/index.js

>run(24, 6, 2, 1337)
TAP version 13
># Full test
>ok 1 should be truthy
>ok 2 should be truthy
>ok 3 should be truthy
>ok 4 should be truthy
>ok 5 should be truthy
>(node:14807) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ok 6 should be equivalent
closing bootstrap client
closing server
closing root node
closing workers

>1..6
># tests 6
># pass  6

># ok

# Any guidance on what I should get pando functional locally will be greatly appreciated.

**Comment by elavoie** [comment]
@csajedi  I am currently traveling and swamped in other things. I should be able to get back to you in about a week. Thanks for your interest in Pando!

**Comment by csajedi** [comment]
Thanks @elavoie , looking forward to getting to the point where I can play around with it. Don't stress about it though, I'm just fiddling with a volunteer computing hobby project.

**Comment by elavoie** [comment]
Hi @csajedi, not quite sure what your problem is. You can use the Docker image, [as described here](https://github.com/elavoie/pando-computing#using-a-pre-configured-docker-image-with-built-in-examples) to test examples. I have also updated the paper that describes Pando on [Arxiv](https://arxiv.org/abs/1803.08426). Hope that makes it clearer and helps you play with it!
